url: https://blog.privacysolutions.no
root: /
permalink: /:categories/:year/:month/:day/:title/
timezone: "Europe/Oslo"
# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : "The privacy solutions project"
tagline: "Privacy solutions - I2P, i2pd, Abscond, Repungo"
description: "This is our official blog where we will blog updates, news and other related information!"
author : 
  name : "The press"
  email : press@privacysolutions.no
  github : PrivacySolutions
  twitter : PSolutions_no
production_url : https://privacysolutions.no
# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections:
  docs:
    output: true

encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: false
limit_posts: 10
future:      false
unpublished: false

# Plugins
whitelist: ['compressor']
gems:      ['redcarpet']



# Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# Conversion
markdown:    redcarpet
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    0.0.0.0
baseurl: "" # does not include hostname

# Backwards-compatibility
relative_permalinks: false

# Outputting
paginate_path: /page:num
paginate: 5

quiet:    false
defaults: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   false

  coderay:
    coderay_wrap:              code
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

redcloth:
  hard_breaks: true
